language: python
python:
 - "3.6"

addons:
  apt:
    packages:
     - make
     - libxml2-utils
     - xsltproc
     - inkscape
     - nodejs

before_install:
 - source ./.travis/common.sh

install:
 - ./.travis/install.sh

script:
 - ./.travis/script.sh

after_success:
 - ./.travis/after_success.sh

after_failure:
 - ./.travis/after_failure.sh
