language: python
python:
 - "3.6"

addons:
  apt:
    packages:
     - bash
     - colordiff
     - coreutils
     - graphviz
     - inkscape
     - make

before_install:
 - source ./.travis/common.sh

install:
 - stdbuf -i0 -o0 -e0 ./.travis/install.sh

script:
 - stdbuf -i0 -o0 -e0 ./.travis/script.sh

after_success:
 - stdbuf -i0 -o0 -e0 ./.travis/after_success.sh

after_failure:
 - stdbuf -i0 -o0 -e0 ./.travis/after_failure.sh
