name: Check all tests

on:
  status:

jobs:
  Check-statuses:
    if: ${{ contains(github.event.branches.*.name, 'master') == 0 }}
    runs-on: ubuntu-latest

    steps:
    - name: Check status
      run: |
        curl -s --url https://api.github.com/repos/${{ github.repository }}/commits/${{ github.event.sha }}/status \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | head -n 2 | tail -n 1 | grep "success"
    - name: Set up Python
      if: ${{ success() }}
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install STPM
      if: ${{ success() }}
      run: pip install git+https://github.com/SymbiFlow/symbiflow-tools-package-manager#egg=stpm
    - name: Get latest artifact name
      if: ${{ success() }}
      run: mkdir output && symbiflow_get_latest_artifact_url > output/latest

